// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrCBCGqtRktLRxGJbEw3Y5urv-BuvSEYQ',
    appId: '1:767697846443:web:6b1093f67be6c4c0ad77ee',
    messagingSenderId: '767697846443',
    projectId: 'scoe-96402',
    authDomain: 'scoe-96402.firebaseapp.com',
    storageBucket: 'scoe-96402.firebasestorage.app',
    measurementId: 'G-GMR4CRLKF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHE8R93dBVCrNdvY8i1QcCqz5IeqZRP_8',
    appId: '1:767697846443:android:3827e4e371e7bdf3ad77ee',
    messagingSenderId: '767697846443',
    projectId: 'scoe-96402',
    storageBucket: 'scoe-96402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPvTyof_0PirC46wgjpaBbJ8goUIgUAU',
    appId: '1:767697846443:ios:5c63f94ebdc3e1a9ad77ee',
    messagingSenderId: '767697846443',
    projectId: 'scoe-96402',
    storageBucket: 'scoe-96402.firebasestorage.app',
    iosBundleId: 'com.example.sgceCollegePredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfPvTyof_0PirC46wgjpaBbJ8goUIgUAU',
    appId: '1:767697846443:ios:5c63f94ebdc3e1a9ad77ee',
    messagingSenderId: '767697846443',
    projectId: 'scoe-96402',
    storageBucket: 'scoe-96402.firebasestorage.app',
    iosBundleId: 'com.example.sgceCollegePredictor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrCBCGqtRktLRxGJbEw3Y5urv-BuvSEYQ',
    appId: '1:767697846443:web:e0bf31a13737d05cad77ee',
    messagingSenderId: '767697846443',
    projectId: 'scoe-96402',
    authDomain: 'scoe-96402.firebaseapp.com',
    storageBucket: 'scoe-96402.firebasestorage.app',
    measurementId: 'G-WFZH7B7L50',
  );
}